services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # host port : docker container port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

networks:             # this is used to create new if it doesnot already exist
  airflow_network:
    external: false

volumes:
  postgres_data: